DIM X AS INTEGER
CLS
FOR X = 1 TO 5
PRINT "how old is bubli"
INPUT name$
PRINT "ENTER MATHS MARKS"
INPUT number1
PRINT "ENTER SCIENCE MARKS"
INPUT number2
SUM = number1 + number2
PRINT "The total is:", SUM
IF SUM < 50 THEN
 PRINT "FAIL"
END IF
IF SUM >= 50 THEN
PRINT "PASS"
END IF
NEXT X